# dataset format:
# data---train---images
# data---train---annotations.json
# data---val---images
# data---val---annotations.json

task: detection

num_classes:  # number of classes + 1
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    # Your own dataset's path
    img_folder: 
    ann_file: 
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 16
  num_workers: 6
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    # Your own dataset's path
    img_folder: 
    ann_file: 
    transforms:
      type: Compose
      ops: ~ 

  shuffle: True
  batch_size: 32
  num_workers: 6
  drop_last: True