__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_swin.yml',
]

output_dir: ./output/rtdetr_swin_base

SwinTransformer:
  arch: 'base'
  depths: [2, 2, 18, 2]
  num_heads: [4, 8, 16, 32]
  drop_rate: 0.0
  attn_drop_rate: 0.0
  drop_path_rate: 0.3

HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5

RTDETRTransformer:
  eval_idx: -1
  num_decoder_layers: 3
  num_denoising: 100

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001 