__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/custom_optimizer.yml',
  './include/rtdetr_convnext.yml',
]

output_dir: ./output/rtdetr_convnext_large

ConvNeXt:
  arch: 'large'
  depths: [3, 3, 27, 3]
  dims: [192, 384, 768, 1536]
  drop_path_rate: 0.4
  
HybridEncoder:
  in_channels: [192, 384, 768]
  hidden_dim: 256
  expansion: 1.0

RTDETRTransformer:
  eval_idx: -1
  num_decoder_layers: 6
  num_denoising: 100

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001 