__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/custom_optimizer.yml',
  './include/rtdetr_swin_spec.yml',
]

output_dir: ./output/rtdetr_swin_large

SwinTransformer:
  arch: 'large'
  depths: [2, 2, 18, 2]
  num_heads: [6, 12, 24, 48]
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.3
  
HybridEncoder:
  in_channels: [192, 384, 768]
  hidden_dim: 256
  expansion: 0.5

RTDETRTransformer:
  eval_idx: -1
  num_queries: 400
  num_decoder_layers: 8
  num_denoising: 100

optimizer:
  type: AdamW

lr_scheduler:
  type: CosineAnnealingLR
