__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_swin.yml',
]

output_dir: ./output/rtdetr_swin_tiny

SwinTransformer:
  arch: 'tiny'
  depths: [2, 2, 6, 2]
  num_heads: [3, 6, 12, 24]
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.
  
HybridEncoder:
  in_channels: [96, 192, 384]
  hidden_dim: 256
  expansion: 1.0  # 减小expansion以降低计算量

RTDETRTransformer:
  eval_idx: -1
  num_decoder_layers: 3  # 减少decoder层数
  num_denoising: 100

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001 